version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  api:
    image: ryanw31/qbxr:api-latest
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - mongodb
    volumes:
      - '/app/node_modules'
      - './server:/app'
    env_file: ./.env
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_PORT=${MONGO_PORT}
    expose:
      - 5001

  client:
    image: ryanw31/qbxr:client-latest
    build: 
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - '/app/node_modules'
      - './client:/app'
    environment:
      - WDS_SOCKET_PORT=0
    expose:
      - 80
    tty: true
    stdin_open: true

  mongodb:
    image: mongo:latest
    container_name: mongodb

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

    ports:
      - "27017:27017"

    volumes:
      - mongodata:/data/db

volumes: 
  mongodata:
