version: '3.8'

# Services
services:
  # Server service
  server:
    image: ryanw31/qbxr:server-latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5001:5001"
    env_file: ./.env
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_PORT=${MONGO_PORT}
    depends_on:
      - mongodb

  client:
    image: ryanw31/qbxr:client-latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - server

  mongodb:
    image: mongo:latest
    container_name: mongodb

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

    ports:
      - "27017:27017"

    volumes:
      - mongodata:/data/db

volumes: 
  mongodata:
