version: '3'
services:
  client:
    image: ryanw31/qbxr:client-latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    develop:
      watch:
        - action: rebuild
          path: ./client
          ignore:
            - node_modules
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - caddy-data:/data
      - caddy-config:/config

  api:
    image: ryanw31/qbxr:api-latest
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./server/package.json
          ignore:
            - node_modules
    ports:
      - 5001:5001
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_PORT=${MONGO_PORT}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EMAIL_SECRET=${JWT_EMAIL_SECRET}
      - POSTMARK_API_KEY=${POSTMARK_API_KEY}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_ININTDB_DATABASE=${MONGO_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./docker-entrypoint-initdb.d/setup.js:/docker-entrypoint-initdb.d/setup.js
    restart: unless-stopped

volumes: 
  mongodata:
  caddy-config:
  caddy-data:
