version: '3'
services:
  api:
    image: ryanw31/qbxr:api-latest
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - '/app/node_modules'
      - './server:/app'
    command: npm start
    env_file: ./.env
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_PORT=${MONGO_PORT}
    depends_on:
      - mongodb

  client:
    image: ryanw31/qbxr:client-latest
    build: 
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - '/app/node_modules'
      - './client:/app'
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - '80:80'
    tty: true
    stdin_open: true

  mongodb:
    image: mongo:latest
    container_name: mongodb

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

    ports:
      - "27017:27017"

    volumes:
      - mongodata:/data/db

volumes: 
  mongodata:
