name: qbxr

services:
  mongodb:
    image: mongo:7.0.12
    volumes:
      - mongo_data:/data/db
    networks:
      - qbxr

  api:
    build:
      context: ./server
      target: production
    restart: unless-stopped
    networks:
      - qbxr
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      target: production
      args:
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - qbxr
    depends_on:
      - api

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - qbxr
    depends_on:
      - client
      - api

volumes:
  mongo_data:
  caddy_data:
  caddy_config:

networks:
  qbxr:
    driver: bridge