version: '3'
services:
  client:
    image: ryanw31/qbxr:client-latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - caddy-data:/data
      - caddy-config:/config

  api:
    image: ryanw31/qbxr:api-latest
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_PORT=${MONGO_PORT}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

volumes: 
  mongodata:
  caddy-config:
  caddy-data:
