name: Build and Deploy
on:
  push:
    branches:
      - main
env:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Install and Test Client
    working-directory: ./client
    run: |
      npm install
      npm test

  - name: Install and Test Server
    working-directory: ./server
    run: |
      npm install
      npm run test
