name: Build and Deploy
on:
  push:
    branches:
      - main

env:
  JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
  JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Test Client
        working-directory: ./client-1
        run: |
          npm install
          npm run test

      - name: Install and Test Server
        working-directory: ./server
        run: |
          npm install
          export JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
          export JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
          export RESEND_API_KEY=$RESEND_API_KEY
          npm run test

      # Exclude node_modules and any other unnecessary files like tests
      - name: Generate deployment package
        run: |
          zip -r deploy.zip * .[^.]* -x "**/node_modules/*" "**/client-1/node_modules/*" "**/server/node_modules/*" "**/*.test.*" "**/__tests__/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_APP_NAME }}
          environment_name: ${{ secrets.AWS_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
          version_label: "version-${{ github.run_number }}"
          deployment_package: deploy.zip
