name: Build and Deploy
on:
  push:
    branches:
      - main
env:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Test Client
        working-directory: ./client
        run: |
          npm install
          npm test

      - name: Install and Test Server
        working-directory: ./server
        run: |
          npm install
          npm run test

      - name: Build Client Docker Image
        working-directory: ./client
        run: |
          docker build -t ryanw31/qbxr:client-${{github.run_number}} .

      - name: Build Server Docker Image
        working-directory: ./server
        run: |
          docker build -t ryanw31/qbxr:server-${{github.run_number}} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker push ryanw31/qbxr:client-${{github.run_number}}
          docker push ryanw31/qbxr:server-${{github.run_number}}
