name: Build and Deploy
on:
  push:
    branches:
      - main

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
  JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Test Client
        working-directory: ./client
        run: |
          npm install
          npm run test

      - name: Install and Test Server
        working-directory: ./server
        run: |
          npm install
          export MONGODB_URI=$MONGODB_URI
          export JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
          export JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
          npm run test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Client Docker Image
        working-directory: ./client
        run: |
          docker build -t ryanw31/qbxr:client-${{github.run_number}} -t ryanw31/qbxr:client-latest .

      - name: Build Server Docker Image
        working-directory: ./server
        run: |
          docker build -t ryanw31/qbxr:server-${{github.run_number}} -t ryanw31/qbxr:server-latest .

      - name: Push Docker Images
        run: |
          docker push ryanw31/qbxr:client-${{github.run_number}}
          docker push ryanw31/qbxr:server-${{github.run_number}}
          docker push ryanw31/qbxr:client-latest
          docker push ryanw31/qbxr:server-latest

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_APP_NAME }}
          environment_name: ${{ secrets.AWS_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
          version_label: "version-${{ github.run_number }}"
          deployment_package: docker-compose.yml
